tasklists:
  DBQL Core:
    tags: [dbql]

  Concurrency:
    tags: [concurrency, performance]
    doc: https://github.com/tdcoa/systasks/wiki/concurrency

  Feature Usage:
    tags: [features]
    doc: https://github.com/tdcoa/systasks/wiki/feature_usage
